//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスによって ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションを付けて
    // /str を使用するか、または Visual Studio プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceElementValue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceElementValue() {
        }
        
        /// <summary>
        ///   このクラスで使用されるキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceElementValue", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、現在のスレッドの CurrentUICulture
        ///   プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ログイン に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Account_Login_btnLogin {
            get {
                return ResourceManager.GetString("Account_Login_btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Account_Login_Password {
            get {
                return ResourceManager.GetString("Account_Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーID に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Account_Login_UserID {
            get {
                return ResourceManager.GetString("Account_Login_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   copyright &amp;copy; {0} Japan Computer Services, Inc. All Rights Reserved. に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layout_CopyRight {
            get {
                return ResourceManager.GetString("Layout_CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layout_link_Back {
            get {
                return ResourceManager.GetString("Layout_link_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layout_link_Home {
            get {
                return ResourceManager.GetString("Layout_link_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layout_link_Logout {
            get {
                return ResourceManager.GetString("Layout_link_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クッキー情報 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_FormsAuthentication_h2_Title {
            get {
                return ResourceManager.GetString("Sample_FormsAuthentication_h2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_FormsAuthentication_th_Name1 {
            get {
                return ResourceManager.GetString("Sample_FormsAuthentication_th_Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_FormsAuthentication_th_Name2 {
            get {
                return ResourceManager.GetString("Sample_FormsAuthentication_th_Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエスト に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_JsonSample_btnRequest_Value {
            get {
                return ResourceManager.GetString("Sample_JsonSample_btnRequest_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セッションキー に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Session_SessionKey {
            get {
                return ResourceManager.GetString("Session_SessionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セッション値 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Session_SessionValue {
            get {
                return ResourceManager.GetString("Session_SessionValue", resourceCulture);
            }
        }
    }
}
