//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスによって ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションを付けて
    // /str を使用するか、または Visual Studio プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceTitle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTitle() {
        }
        
        /// <summary>
        ///   このクラスで使用されるキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceTitle", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、現在のスレッドの CurrentUICulture
        ///   プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ログイン に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Account_Login_Title {
            get {
                return ResourceManager.GetString("Account_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Home_Index_Title {
            get {
                return ResourceManager.GetString("Home_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JCS Sample Application に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_Exception_Index_Title {
            get {
                return ResourceManager.GetString("Sample_Exception_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FormsAuthentication に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_FormsAuthentication_Index_Title {
            get {
                return ResourceManager.GetString("Sample_FormsAuthentication_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C# to Json に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_JsonSample_Index_Title {
            get {
                return ResourceManager.GetString("Sample_JsonSample_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calendar に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_Plugin_Calendar_Title {
            get {
                return ResourceManager.GetString("Sample_Plugin_Calendar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Handsontable に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_Plugin_Handsontable_Title {
            get {
                return ResourceManager.GetString("Sample_Plugin_Handsontable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ImageGallery に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_Plugin_ImageGallery_Title {
            get {
                return ResourceManager.GetString("Sample_Plugin_ImageGallery_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Session に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_Plugin_Session_Title {
            get {
                return ResourceManager.GetString("Sample_Plugin_Session_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ResultSample に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_ResultSample_Index_Title {
            get {
                return ResourceManager.GetString("Sample_ResultSample_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サンプルアプリ に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_SampleHome_Index_Title {
            get {
                return ResourceManager.GetString("Sample_SampleHome_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_User_Create_Title {
            get {
                return ResourceManager.GetString("Sample_User_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_User_Delete_Title {
            get {
                return ResourceManager.GetString("Sample_User_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_User_Details_Title {
            get {
                return ResourceManager.GetString("Sample_User_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_User_Edit_Title {
            get {
                return ResourceManager.GetString("Sample_User_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー一覧画面 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_User_Index_Title {
            get {
                return ResourceManager.GetString("Sample_User_Index_Title", resourceCulture);
            }
        }
    }
}
