//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスによって ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションを付けて
    // /str を使用するか、または Visual Studio プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessage() {
        }
        
        /// <summary>
        ///   このクラスで使用されるキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceMessage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、現在のスレッドの CurrentUICulture
        ///   プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   サンプルアプリケーションを作成する場合は、リンク先の画面に作成してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Home_Sample_SampleHome_Index_About {
            get {
                return ResourceManager.GetString("Home_Sample_SampleHome_Index_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインしてください に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Login_Please_Login {
            get {
                return ResourceManager.GetString("Login_Please_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタンをクリックすると、Exceptionが発生する。&lt;br /&gt;テスト用。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_SampleHome_Exception_Index_About {
            get {
                return ResourceManager.GetString("Sample_SampleHome_Exception_Index_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クッキー情報を表示してくれるサンプル。&lt;br /&gt;ログイン情報等、表示させている。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_SampleHome_FormsAuthentication_Index_About {
            get {
                return ResourceManager.GetString("Sample_SampleHome_FormsAuthentication_Index_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーの一覧、登録、削除、編集、詳細のサンプル画面。&lt;br /&gt;一覧の表示には&lt;a href=&quot;https://datatables.net/&quot; target=&quot;_blank&quot;&gt;datatables&lt;/a&gt;を使用している。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_SampleHome_Index_User_About {
            get {
                return ResourceManager.GetString("Sample_SampleHome_Index_User_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ModelからJsonを作成してくれるサンプル。&lt;br /&gt;便利だと思われるが、まだ試作段階。&lt;br /&gt;&lt;a href=&quot;http://json2csharp.com/&quot;&gt;json2csharp&lt;/a&gt;このこのサイトの機能を参考に作ってみている。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_SampleHome_JsonSample_Index_About {
            get {
                return ResourceManager.GetString("Sample_SampleHome_JsonSample_Index_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;a href=&quot;http://fullcalendar.io/&quot; target=&quot;_blank&quot;&gt;FullCalendar&lt;/a&gt;と&lt;a href=&quot;https://eonasdan.github.io/bootstrap-datetimepicker/&quot; target=&quot;_blank&quot;&gt;Bootstrap-DatePicker&lt;/a&gt;のサンプル。&lt;br /&gt;FullCalendarは現在は表示しているだけ。DatePickerは日本語化対応されている。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_SampleHome_Plugin_Calendar_About {
            get {
                return ResourceManager.GetString("Sample_SampleHome_Plugin_Calendar_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Handsontableのサンプル。&lt;br /&gt;動きはするが、まだ作成中の段階。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_SampleHome_Plugin_Handsontable_About {
            get {
                return ResourceManager.GetString("Sample_SampleHome_Plugin_Handsontable_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   blueimp Galleryという、イメージ＆ビデオ用のギャラリーを表示できるサンプル。&lt;br /&gt;少しだけ、挙動がおかしいところがあるが、動いてはいる。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_SampleHome_Plugin_ImageGallery_About {
            get {
                return ResourceManager.GetString("Sample_SampleHome_Plugin_ImageGallery_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セッションに値を入れて、それを表示させるサンプル。&lt;br /&gt;一覧の表示には&lt;a href=&quot;https://datatables.net/&quot; target=&quot;_blank&quot;&gt;datatables&lt;/a&gt;を使用している。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_SampleHome_Plugin_Session_About {
            get {
                return ResourceManager.GetString("Sample_SampleHome_Plugin_Session_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクション時の結果を通知する方法を見せるための、サンプル。&lt;br /&gt;いらないかも。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample_SampleHome_ResultSample_Index_About {
            get {
                return ResourceManager.GetString("Sample_SampleHome_ResultSample_Index_About", resourceCulture);
            }
        }
    }
}
