//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5Template.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceError() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC5Template.App_GlobalResources.ResourceError", typeof(ResourceError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ユーザーIDまたはパスワードが間違っています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login_LoginError_ErrorMessage {
            get {
                return ResourceManager.GetString("Login_LoginError_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードを入れてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login_Password_ErrorMessage_Required {
            get {
                return ResourceManager.GetString("Login_Password_ErrorMessage_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーIDは数字以外入力できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login_UserID_ErrorMessage_RegularExpression {
            get {
                return ResourceManager.GetString("Login_UserID_ErrorMessage_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーIDを入れてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login_UserID_ErrorMessage_Required {
            get {
                return ResourceManager.GetString("Login_UserID_ErrorMessage_Required", resourceCulture);
            }
        }
    }
}
